version: "2.2"
services:
  rabbitmq:
    image: it490/rabbitmq
    ports:
      - "80:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://elk.lan:5000"
        syslog-format: "rfc3164"
        syslog-facility: "daemon"
        tag: "rabbitmq"

volumes:
  rabbitmq:

