version: "2.2"
services:
  imdbscraper:
    image: it490/imdbscraper
    restart: on-failure
    environment:
      APP_QUEUE_URL: "amqp://root:root@rabbitmq.lan:5672/%2F"
      APP_QUEUE_TOPIC_APP: "requests-app"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://elk.lan:5000"
        syslog-format: "rfc3164"
        syslog-facility: "daemon"
        tag: "imdbscraper"

  weatherscraper:
    image: it490/weatherscraper
    restart: on-failure
    environment:
      APP_QUEUE_URL: "amqp://root:root@rabbitmq.lan:5672/%2F"
      APP_QUEUE_TOPIC_APP: "requests-weather"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://elk.lan:5000"
        syslog-format: "rfc3164"
        syslog-facility: "daemon"
        tag: "weatherscraper"
