version: "2.2"
services:
  app:
    image: it490/app
    restart: on-failure
    environment:
      APP_QUEUE_URL: "amqp://root:root@rabbitmq.lan:5672/%2F"
      APP_QUEUE_TOPIC_APP: "requests-app"
      APP_QUEUE_TOPIC_WEATHER: "requests-weather"
      APP_DATABASE_URL: "mysql+pymysql://app:app@mysql:3306/app"

  mysql:
    image: mariadb:10.4.8-bionic
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app

volumes:
  mysql:

